# Bibliotecas

#### => ARRAYS N-DIMENSIONAIS PODEROSOS
    Rápido e versátil, os conceitos de vetorização, indexação e transmissão do NumPy são os padrões de fato da computação em array hoje.


#### => FERRAMENTAS DE COMPUTAÇÃO NUMÉRICA
    O NumPy oferece funções matemáticas abrangentes, geradores de números aleatórios, rotinas de álgebra linear, transformadas de Fourier e muito mais.

#### => INTEROPERÁVEL
    O NumPy oferece suporte a uma ampla variedade de plataformas de hardware e computação e funciona bem com bibliotecas distribuídas, GPU e de matriz esparsa.


#### => PERFORMANTE
    O núcleo do NumPy é um código C bem otimizado. Aproveite a flexibilidade do Python com a velocidade do código compilado.

#### => FÁCIL DE USAR
    A sintaxe de alto nível do NumPy o torna acessível e produtivo para programadores de qualquer formação ou nível de experiência.

#### => CÓDIGO ABERTO
    Distribuído sob uma licença BSD liberal , o NumPy é desenvolvido e mantido publicamente no GitHub por uma comunidade vibrante, ágil e diversa.


Documentação  [NUMPY](https://numpy.org/)

### Matriz ou **array**

Uma matriz é uma estrutura de dados central da biblioteca NumPy. Uma matriz é uma grade de valores e contém informações sobre os dados brutos, como localizar um elemento e como interpretar um elemento. Possui uma grade de elementos que podem ser indexados de várias maneiras. Os elementos são todos do mesmo tipo, referidos como array dtype

In [1]:
import numpy as np

Criando uma matriz

In [2]:
matriz = np.array([1,2,3,4]) 

In [3]:
matriz

array([1, 2, 3, 4])

Preenchendo automaticamente a matriz

In [6]:
matriz = np.arange(23)
matriz

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [12]:
matriz_aleatoria=np.random.rand(10)
matriz_aleatoria

array([0.34227916, 0.69959967, 0.25990999, 0.0864966 , 0.1960255 ,
       0.86721408, 0.21515574, 0.55475783, 0.12068736, 0.67274381])

In [13]:
matriz_ruido = np.random.rand(10)+5
matriz_ruido

array([5.84423848, 5.01440611, 5.48164707, 5.44843964, 5.99988157,
       5.39895467, 5.53468736, 5.19716515, 5.15470715, 5.7365942 ])

### Mudando o formato da matriz

In [16]:
a = np.arange(20).reshape(4, 5)  #arange preenche a matriz com um range de 0 a 19 com 4 linhas e 5 colunas

In [17]:
a

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
b = np.random.rand(10).reshape(2,5)+7
b

array([[7.26566011, 7.80149389, 7.95091871, 7.38870092, 7.13535652],
       [7.56036012, 7.9051892 , 7.63363976, 7.55413448, 7.62828568]])

Uma matriz pode ser indexada por uma tupla de inteiros não negativos, por booleanos, por outra matriz ou por inteiros. O rank da matriz é o número de dimensões. O shapeda matriz é uma tupla de inteiros fornecendo o tamanho da matriz ao longo de cada dimensão.

Uma maneira de inicializar matrizes NumPy é a partir de listas Python, usando listas aninhadas para dados bidimensionais ou superiores.

In [23]:
b = np.array([(1.8,2,5), (2,7,9.3)])  #com numeros float

In [24]:
b

array([[1.8, 2. , 5. ],
       [2. , 7. , 9.3]])

In [25]:
c = np.array( [ [5+1j,7], [6,8] ], dtype=complex ) #com numeros complexos
c

array([[5.+1.j, 7.+0.j],
       [6.+0.j, 8.+0.j]])

In [26]:
matriz1 = np.array([2, 25, 13, 4, 25, 36])


In [27]:
matriz1

array([ 2, 25, 13,  4, 25, 36])

In [28]:
type(matriz1)

numpy.ndarray

In [29]:
matriz1.shape

(6,)

In [30]:
matriz36 = np.array([[2, 25, 13, 4, 25, 36],[44, 15, 18, 4, 27, 39],[22, 55, 43, 54, 5, 6]])

In [31]:
type(matriz36)

numpy.ndarray

In [32]:
matriz36

array([[ 2, 25, 13,  4, 25, 36],
       [44, 15, 18,  4, 27, 39],
       [22, 55, 43, 54,  5,  6]])

In [33]:
print("\n",matriz36[0])  # mudando a ordem quando impresso
print("\n",matriz36[2])
print("\n",matriz36[1])


 [ 2 25 13  4 25 36]

 [22 55 43 54  5  6]

 [44 15 18  4 27 39]


In [34]:
np.arange(0, 10, 2) #de 2 a 9 com passo de 2

array([0, 2, 4, 6, 8])

In [35]:
matriz36

array([[ 2, 25, 13,  4, 25, 36],
       [44, 15, 18,  4, 27, 39],
       [22, 55, 43, 54,  5,  6]])

In [36]:
np.sort(matriz36)

array([[ 2,  4, 13, 25, 25, 36],
       [ 4, 15, 18, 27, 39, 44],
       [ 5,  6, 22, 43, 54, 55]])

In [37]:
matriz36.size

18

In [38]:
matriz36.ndim #matriz tem dimensoes x e y neste exemplo

2

In [39]:
matriz36.shape

(3, 6)

In [40]:
matriz36.itemsize #Comprimento de um elemento da matriz em bytes.

8

In [41]:
m = np.array([1,2,5], dtype=np.complex128)
m

array([1.+0.j, 2.+0.j, 5.+0.j])

In [42]:
m.itemsize

16

### Outras estruturas de matrizes

NumPy oferece várias funções para criar arrays com conteúdo inicial de espaço reservado. Isso minimiza a necessidade de aumentar matrizes, uma operação cara.

A função zeros cria um array cheio de zeros, a função uns cria um array cheio de uns e a função empty cria um array cujo conteúdo inicial é aleatório e depende do estado da memória. 
Por padrão, o dtype da matriz criada é float64.

In [ ]:
np.zeros((4, 3)) #Cria 1 matriz de 4 linhas por 3 colunas com valores 0 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones( (3,4,5), dtype=np.int32 ) #Cria 3 matrizes de 4 linhas por 5 colunas e especifica o tipo dos elementos para int32

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int32)

In [ ]:
 np.empty( (3,4) ) #Cria uma matriz 'vazia'

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.empty(2)

array([1., 1.])

### Criando matrizes lineares

In [ ]:
np.linspace(0, 20, num=5) # Faixa de valores entre 0 e 20, sendo "num" a uqnatidade de valores

array([ 0.,  5., 10., 15., 20.])

### Trabalhando com matrizes

In [ ]:
matriz = np.array([4,8,34,5,23,1,7,19,21,20,20,8])

In [ ]:
matriz

array([ 4,  8, 34,  5, 23,  1,  7, 19, 21, 20, 20,  8])

#### Ordenando valores de uma matriz 

In [ ]:
np.sort(matriz)

array([ 1,  4,  5,  7,  8,  8, 19, 20, 20, 21, 23, 34])

Além de sort, que retorna uma cópia classificada de uma matriz, você pode usar:

- **argsort**, que é uma ordenacao indireta ao longo de um eixo especificado,
- **lexsort**, que é uma ordenacao estável indireta em várias chaves,
- **searchsorted**, que encontrará elementos em uma matriz ordenada, e
- **partition**, que é uma ordenacao parcial.

#### Concatenando matrizes

In [ ]:
m = np.array([2,5,3,2])

In [ ]:
n = np.array([2,7,9,5])

In [ ]:
z = np.concatenate((m, n))
z

array([2, 5, 3, 2, 2, 7, 9, 5])

In [ ]:
np.sort(z)

array([2, 2, 2, 3, 5, 5, 7, 9])

#### Remodelando a matriz

In [ ]:
m1 = np.arange(12) #numero de elementos 12

In [ ]:
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
m2 = m1.reshape(3, 4) #Numero de elementos na matriz 3x4=12...
m2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Apresentando elementos da matriz

In [ ]:
dados = np.array([1, 2, 3,5,8,12,9])



In [ ]:
dados[1]

2

In [ ]:
dados[1:]

array([ 2,  3,  5,  8, 12,  9])

In [ ]:
dados[-2]

12

In [ ]:
dados[2:5]

array([3, 5, 8])

In [ ]:
matrizdf = np.array([['Joao',25,1995,2016],['Maria',47,1973,2000],['Luisa',38,1982,2005]], dtype=object)

In [ ]:
matrizdf

array([['Joao', 25, 1995, 2016],
       ['Maria', 47, 1973, 2000],
       ['Luisa', 38, 1982, 2005]], dtype=object)

### Multiplicando Matrizes

O princípio de multiplicação de matrizes
**(n,k),(k,m)->(n,m)**

In [43]:
m1=(23,12,6)
m2=(5,7,3)


O que acontece se multiplico uma matriz por um número?

In [44]:
m3=3*m1
m3

(23, 12, 6, 23, 12, 6, 23, 12, 6)

Como podemos realizar multiplicações?

In [52]:
np.dot(4,6)

24

In [55]:
m1

(23, 12, 6)

In [54]:
np.dot(3,m1)

array([69, 36, 18])

Multiplicando duas matrizes de mesmas dimensões

In [56]:
ma = [[1, 0], [0, 1]]
mb = [[4, 1], [2, 2]]
np.dot(ma, mb)

array([[4, 1],
       [2, 2]])

In [50]:
ma = np.array([[5, 3],
              [0, 1]])
mb = np.array([[2, 3],
              [1, 0]])
print(ma)
print(mb)

[[5 3]
 [0 1]]
[[2 3]
 [1 0]]


In [51]:
np.matmul(ma, mb)

array([[13, 15],
       [ 1,  0]])